package test

import (
	"encoding/base64"
)

// this is a self-signed x509 cert generated by OpenSSL. Ingore the fact that it's a certificate; Used as test data because x509 is full of weird binary data values, increasing our likelihood of catching signed/unsigned mismatch bugs.
var testData, _ = base64.StdEncoding.DecodeString("MIICBDCCAaugAwIBAgIUGNg/B3GL5BId8KGNdhD6+NejvsQwCgYIKoZIzj0EAwIwWDELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxFzAVBgNVBAoMDk9jdG9wdXMgRGVwbG95MQwwCgYDVQQLDANSJkQxDTALBgNVBAMMBFRFU1QwHhcNMjMwMzIwMDk0ODQyWhcNMjQwMzE5MDk0ODQyWjBYMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEXMBUGA1UECgwOT2N0b3B1cyBEZXBsb3kxDDAKBgNVBAsMA1ImRDENMAsGA1UEAwwEVEVTVDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFBLdySNg+Lj4gm7sil6Dk0k/0Xnnv+I3RZeZBmumFEtq9IhnaRuk9f/mNWhy4AxSlfzfQkx7PfzvUvOISz9LLqjUzBRMB0GA1UdDgQWBBS63SeKMeASd2r7/aTq2P3OkE8O/DAfBgNVHSMEGDAWgBS63SeKMeASd2r7/aTq2P3OkE8O/DAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIFmc75IBFbZKfQvH3lWoS7p/Be54uekDr3y1K0pdzI6iAiAGV1RF2rnCEyWkjeO9fOUaNGEgFadGSHh8en4DJkU3cA==")

func min(a int, b int) int {
	if a < b {
		return a
	}
	return b
}

func TestData() []byte {
	return GenerateTestData(len(testData))
}

// generates arbitrary length test data by repeating copies of our dummy x509 certificate
func GenerateTestData(byteCount int) []byte {
	testDataLen := len(testData)
	result := make([]byte, byteCount)

	for offset := 0; offset <= byteCount; offset += testDataLen {
		copy(result[offset:offset+min(testDataLen, byteCount-offset)], testData)
	}

	return result
}
